# general settings
name: DAPE
model_type: DAPEModel
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 10
ram_model_path: /home/hyunseo/workspace/sar2opt/recognize-anything/ram_swin_large_14m.pth

# dataset and data loader settings
datasets:
  train:
    name: train_dataset
    type: DAPEDataset
    root: ['/home/hyunseo/workspace/sar2opt/datasets']
    ext: ['*.png']
    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    

# network structures
network_g: ram_swin_bert_lora


# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 30000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: 50  # no warm up

  cri_feature_opt:
    type: L1Loss # or MSELoss
    loss_weight: 1.0 # This will be overridden by lambda_rep
    reduction: mean
  
  cri_logits_opt:
    type: BCELoss # Use built-in BCE for stability
    loss_weight: 1.0 # This will be overridden by lambda_tag
    reduction: mean

  lambda_rep: 1.0
  lambda_tag: 1.0
  lambda_mmd: 1.0

  warmup_iter: 20000 # e.g., 20k iterations for warmup
  temp_start: 5.0    # Initial high temperature
  temp_end: 1.0      # Final temperature

# validation settings
val:
  val_freq: !!float 1e8 # !!float 5e3
  save_img: false

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 1e3 # !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500